/** Static starter files (generated by `scripts/generate-ats-resume-assets.mjs`). */
export const ATS_RESUME_TEMPLATE_DOCX_HREF = "/downloads/ats-resume-template.docx" as const;
export const ATS_RESUME_TEMPLATE_TXT_HREF = "/downloads/ats-resume-template.txt" as const;
