import type { RoleSlug } from "@/app/lib/seoPages";

export type RoleContent = {
  tools: string[];
  domainVerbs: string[];
  examplePhrases: string[];
  topKeywords?: string[];
  exampleBullets?: string[];
  keywordClusters?: {
    backend?: string[];
    frontend?: string[];
    devops?: string[];
    data?: string[];
    tools?: string[];
    concepts?: string[];
  };
  keywordMistakes?: string[];
};

export const ROLE_CONTENT_MAP: Record<RoleSlug, RoleContent> = {
  "software-engineer": {
    tools: ["TypeScript", "Node.js", "AWS", "PostgreSQL", "CI/CD"],
    domainVerbs: ["shipped", "scaled", "refactored", "optimized", "stabilized"],
    examplePhrases: [
      "Reduced API latency by 35% with query and caching improvements.",
      "Shipped production features with feature flags and rollout monitoring.",
      "Improved test reliability by expanding integration and contract coverage.",
    ],
    topKeywords: [
      "TypeScript",
      "JavaScript",
      "React",
      "Next.js",
      "Node.js",
      "REST APIs",
      "GraphQL",
      "PostgreSQL",
      "AWS",
      "Docker",
      "CI/CD",
      "Unit testing",
      "Integration testing",
      "Performance optimization",
      "Microservices",
    ],
    exampleBullets: [
      "Built and optimized REST APIs in Node.js and PostgreSQL, reducing p95 response latency by 35% for core checkout endpoints.",
      "Implemented CI/CD with GitHub Actions and Docker, cutting average deployment time from 28 to 9 minutes.",
      "Refactored React + TypeScript UI modules, reducing production error rate by 22% and improving Lighthouse performance score by 14 points.",
      "Expanded unit and integration test coverage from 58% to 84%, reducing post-release regressions by 31% quarter-over-quarter.",
      "Designed caching and query-index strategy for high-traffic services, lowering infra cost by 18% without reliability trade-offs.",
    ],
    keywordClusters: {
      backend: ["Node.js", "REST APIs", "GraphQL", "PostgreSQL", "Microservices"],
      frontend: ["React", "Next.js", "TypeScript", "State management", "Web performance"],
      devops: ["AWS", "Docker", "CI/CD", "Monitoring", "Infrastructure as Code"],
    },
    keywordMistakes: [
      "Listing frameworks without showing where you used them in shipped features.",
      "Using generic bullets that omit scale, latency, reliability, or user impact.",
      "Stuffing the skills section with tools that never appear in experience bullets.",
      "Ignoring role-specific keywords from the target job description.",
    ],
  },
  "data-scientist": {
    tools: ["Python", "SQL", "scikit-learn", "XGBoost", "A/B testing"],
    domainVerbs: ["modeled", "experimented", "evaluated", "validated", "forecasted"],
    examplePhrases: [
      "Improved retention by 7% through experiment-backed model updates.",
      "Built churn models and translated findings into lifecycle actions.",
      "Reduced false positives using threshold tuning and calibration analysis.",
    ],
    topKeywords: [
      "Python",
      "SQL",
      "Machine Learning",
      "A/B testing",
      "scikit-learn",
      "XGBoost",
      "TensorFlow",
      "Feature engineering",
      "Model evaluation",
      "Data pipelines",
      "Experiment design",
      "Statistical analysis",
      "Forecasting",
      "NLP",
      "Dashboarding",
    ],
    exampleBullets: [
      "Built machine learning models using Python and XGBoost, improving churn prediction recall by 18% while maintaining precision targets.",
      "Designed and analyzed A/B tests in SQL cohorts, lifting activation by 11% with statistically significant results.",
      "Implemented feature engineering workflows for 12M+ events, reducing model error (MAPE) by 16% quarter-over-quarter.",
      "Automated KPI dashboards and experiment readouts, cutting weekly reporting time from 6 hours to 90 minutes.",
      "Calibrated model thresholds and retraining triggers, reducing false-positive alerts by 24% in production scoring.",
    ],
    keywordClusters: {
      data: ["Python", "SQL", "Machine Learning", "Experimentation", "Model evaluation"],
      tools: ["scikit-learn", "XGBoost", "TensorFlow", "dbt", "Looker"],
      concepts: ["Feature engineering", "A/B testing", "Statistical significance", "Forecasting", "Data quality"],
    },
    keywordMistakes: [
      "Listing ML libraries without tying them to business outcomes.",
      "Using model buzzwords without metrics like lift, precision, recall, or error reduction.",
      "Ignoring experiment and SQL terms repeated in the posting.",
      "Stuffing skills without showing usage in projects or work bullets.",
    ],
  },
  "product-manager": {
    tools: ["Amplitude", "SQL", "Jira", "Figma", "A/B testing"],
    domainVerbs: ["prioritized", "launched", "defined", "aligned", "iterated"],
    examplePhrases: [
      "Prioritized roadmap work tied to activation and retention targets.",
      "Launched onboarding improvements that increased conversion by 10%.",
      "Aligned engineering, design, and GTM around a measurable release plan.",
    ],
    topKeywords: [
      "Product roadmap",
      "Product discovery",
      "User research",
      "PRD",
      "OKRs",
      "A/B testing",
      "SQL",
      "Amplitude",
      "Jira",
      "Stakeholder management",
      "Go-to-market",
      "Activation",
      "Retention",
      "Conversion rate",
      "Prioritization",
      "Backlog grooming",
      "Agile",
      "Scrum",
      "Figma",
      "Metrics-driven",
    ],
    exampleBullets: [
      "Prioritized Q3 roadmap using RICE and activation data, shipping three experiments that lifted trial-to-paid conversion by 9%.",
      "Led discovery with 18 customer interviews and usability tests, reducing rework on the billing squad by 30%.",
      "Defined PRDs and acceptance criteria with engineering and design, improving on-time release rate from 72% to 91%.",
      "Partnered with GTM on launch playbooks for a tiered pricing release, contributing to 14% expansion revenue in two quarters.",
      "Built Amplitude dashboards for funnel and cohort KPIs, cutting weekly exec reporting prep from 6 hours to 90 minutes.",
      "Ran A/B tests on onboarding with guardrail metrics, selecting a variant that increased day-7 retention by 6 points.",
    ],
    keywordMistakes: [
      "Listing roadmap tools without launch outcomes or metrics.",
      "Generic ‘worked with stakeholders’ lines with no decision or trade-off.",
      "Copying JD buzzwords into skills with no supporting bullets.",
      "Omitting discovery or experimentation language when the posting requires it.",
    ],
  },
  "data-analyst": {
    tools: ["SQL", "Looker", "Tableau", "Excel", "dbt"],
    domainVerbs: ["analyzed", "segmented", "reported", "diagnosed", "benchmarked"],
    examplePhrases: [
      "Identified funnel drop-off and improved activation by 8%.",
      "Built stakeholder dashboards for weekly KPI and cohort reviews.",
      "Standardized reporting definitions across marketing and finance teams.",
    ],
    topKeywords: [
      "SQL",
      "Excel",
      "Tableau",
      "Looker",
      "dbt",
      "A/B testing",
      "Cohort analysis",
      "Funnel analysis",
      "Data visualization",
      "Dashboarding",
      "KPI reporting",
      "Data quality",
      "ETL",
      "Stakeholder reporting",
      "Forecasting",
      "Retention analysis",
      "Attribution",
      "Segmentation",
      "Business intelligence",
      "Root cause analysis",
    ],
    exampleBullets: [
      "Used SQL and dbt models to standardize funnel definitions across product and marketing, reducing KPI discrepancies by 41% across weekly reporting.",
      "Built executive Tableau dashboards for acquisition, activation, and retention, cutting ad-hoc analysis turnaround from 2 days to 4 hours.",
      "Ran cohort and segmentation analysis in Looker and Excel, identifying onboarding drop-off drivers and improving activation by 8.3%.",
      "Designed experiment readouts for A/B tests, validating pricing page changes that lifted trial-to-paid conversion by 6.1%.",
      "Diagnosed paid channel CAC drift through attribution analysis, helping reallocate budget and improve blended ROAS by 14% in one quarter.",
      "Automated recurring KPI reporting pipelines, saving ~11 analyst hours per week and improving stakeholder decision latency.",
    ],
    keywordClusters: {
      data: ["Funnel analysis", "Cohort analysis", "Segmentation", "Root cause analysis", "Attribution"],
      tools: ["SQL", "Looker", "Tableau", "Excel", "dbt"],
      concepts: ["A/B testing", "KPI reporting", "Data quality", "Business intelligence", "Forecasting"],
    },
    keywordMistakes: [
      "Listing SQL, Tableau, or Looker without showing one outcome metric tied to each tool.",
      "Using vague bullets like 'created reports' without decision impact, speed, or revenue context.",
      "Stuffing ATS keywords in skills but omitting them from experience and project bullets.",
      "Ignoring role-level language (entry, mid, senior) required in the target posting.",
    ],
  },
  "business-analyst": {
    tools: ["Power BI", "SQL", "BPMN", "Jira", "Confluence"],
    domainVerbs: ["mapped", "elicited", "translated", "facilitated", "documented"],
    examplePhrases: [
      "Mapped current-state processes and identified automation opportunities.",
      "Translated stakeholder requirements into delivery-ready user stories.",
      "Reduced SLA breaches by clarifying workflow handoffs and ownership.",
    ],
    topKeywords: [
      "Requirements gathering",
      "Business requirements document",
      "User stories",
      "Acceptance criteria",
      "Process mapping",
      "BPMN",
      "Stakeholder management",
      "SQL",
      "Power BI",
      "Jira",
      "Confluence",
      "UAT",
      "Gap analysis",
      "As-is / To-be",
      "Agile",
      "Scrum",
      "Workflow optimization",
      "Root cause analysis",
      "Functional specifications",
      "Cross-functional facilitation",
    ],
    exampleBullets: [
      "Elicited requirements from 12 stakeholders across finance and operations, reducing change requests after sprint 2 by 35%.",
      "Documented as-is/to-be BPMN flows for order-to-cash, identifying automation that saved ~900 hours annually.",
      "Authored user stories and acceptance criteria in Jira for a billing modernization, cutting UAT defects by 28%.",
      "Built Power BI dashboards for SLA and backlog health, improving executive visibility into delivery risks.",
      "Facilitated workshops to prioritize a 40-item backlog, aligning three squads on a single release train.",
      "Ran SQL validation on migrated customer records, surfacing data quality issues before go-live and avoiding rework.",
    ],
    keywordMistakes: [
      "Saying ‘gathered requirements’ without artifacts (BRD, stories, diagrams).",
      "Listing Agile terms with no ceremony or delivery outcomes.",
      "Confusing business analyst work with data analyst modeling unless the JD asks for it.",
      "Keyword stuffing tools never mentioned in experience bullets.",
    ],
    keywordClusters: {
      data: ["Requirements traceability", "Gap analysis", "Root cause analysis", "UAT", "Change management"],
      tools: ["Power BI", "SQL", "Jira", "Confluence", "Visio"],
      concepts: ["BPMN", "User stories", "Acceptance criteria", "Stakeholder alignment", "Process improvement"],
    },
  },
  "frontend-developer": {
    tools: ["React", "Next.js", "TypeScript", "Storybook", "Playwright"],
    domainVerbs: ["implemented", "improved", "instrumented", "tested", "hardened"],
    examplePhrases: [
      "Improved Core Web Vitals and raised conversion on key pages.",
      "Built reusable UI components that reduced duplicate code.",
      "Improved accessibility compliance for keyboard and screen-reader users.",
    ],
    topKeywords: [
      "React",
      "TypeScript",
      "JavaScript",
      "Next.js",
      "HTML",
      "CSS",
      "Responsive design",
      "Accessibility",
      "WCAG",
      "Core Web Vitals",
      "Storybook",
      "Jest",
      "Playwright",
      "State management",
      "REST APIs",
      "GraphQL",
      "Webpack",
      "Performance optimization",
      "Design systems",
      "Cross-browser compatibility",
    ],
    exampleBullets: [
      "Rebuilt marketing pages in Next.js and React, improving Lighthouse performance score from 62 to 91 and lifting signup CTR by 11%.",
      "Created a Storybook design system used by four squads, reducing duplicate UI code and cutting feature UI time by ~25%.",
      "Implemented WCAG 2.1 AA fixes for forms and navigation, reducing accessibility-related support tickets by 40%.",
      "Instrumented funnels with analytics hooks and A/B-ready components, enabling faster experiment iteration for product.",
      "Added Playwright end-to-end coverage for checkout flows, reducing regression escapes in production releases.",
      "Optimized bundle size and lazy loading for dashboard routes, cutting median load time by 1.8 seconds on mobile.",
    ],
    keywordMistakes: [
      "Listing frameworks without pages or features you shipped.",
      "Claiming accessibility without concrete WCAG or audit work.",
      "Ignoring performance metrics (LCP, CLS) when the JD stresses web vitals.",
      "Skills-only React lists with no testing or API integration context.",
    ],
    keywordClusters: {
      frontend: ["React", "Next.js", "TypeScript", "CSS", "Responsive design"],
      data: ["REST APIs", "GraphQL", "JSON", "State management", "Caching"],
      concepts: ["Accessibility", "Core Web Vitals", "Design systems", "E2E testing", "Performance"],
    },
  },
  "backend-developer": {
    tools: ["Node.js", "Java", "Redis", "PostgreSQL", "Docker"],
    domainVerbs: ["designed", "secured", "cached", "deployed", "monitored"],
    examplePhrases: [
      "Designed resilient APIs handling high-throughput traffic.",
      "Cut response times with index tuning and cache strategy updates.",
      "Improved deployment reliability with containerized rollout pipelines.",
    ],
    topKeywords: [
      "Node.js",
      "Java",
      "REST APIs",
      "Microservices",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "AWS",
      "CI/CD",
      "System design",
      "Caching",
      "Query optimization",
      "Authentication",
      "Authorization",
      "Message queues",
      "Observability",
      "Rate limiting",
      "Fault tolerance",
      "Incident response",
    ],
    exampleBullets: [
      "Designed and shipped REST APIs in Node.js and PostgreSQL for checkout workflows, reducing p95 latency from 380ms to 230ms under peak load.",
      "Introduced Redis caching and query-plan optimization for high-traffic endpoints, cutting database CPU by 29% while preserving consistency constraints.",
      "Implemented idempotent payment retry logic with queue-backed workers, reducing failed recoverable transactions from 3.8% to 0.9%.",
      "Hardened auth middleware with role-based authorization checks and audit logging, eliminating repeated permission regressions in release cycles.",
      "Containerized backend services and standardized CI/CD deployment gates, reducing rollback incidents by 41% quarter-over-quarter.",
      "Built observability dashboards and alert thresholds for API error budgets, cutting median incident triage time from 37 to 14 minutes.",
    ],
    keywordClusters: {
      backend: ["Node.js", "Java", "REST APIs", "Microservices", "PostgreSQL"],
      devops: ["Docker", "Kubernetes", "AWS", "CI/CD", "Observability"],
      data: ["Redis", "Caching", "Query optimization", "Message queues", "Rate limiting"],
    },
    keywordMistakes: [
      "Listing backend frameworks without tying them to latency, reliability, or throughput outcomes.",
      "Using vague bullets like 'built APIs' without scale, domain, or measurable impact context.",
      "Ignoring security terms from the posting (auth, authorization, auditability) when they are role requirements.",
      "Stuffing tools in skills while omitting them from experience bullets where ATS gives stronger weight.",
    ],
  },
  "machine-learning-engineer": {
    tools: ["Python", "PyTorch", "TensorFlow", "MLflow", "Kubernetes"],
    domainVerbs: ["trained", "deployed", "monitored", "retrained", "serving"],
    examplePhrases: [
      "Deployed model inference endpoints with drift monitoring.",
      "Improved precision and recall through feature engineering and tuning.",
      "Reduced model incidents with retraining triggers and data quality checks.",
    ],
    topKeywords: [
      "Machine learning",
      "Deep learning",
      "Python",
      "PyTorch",
      "TensorFlow",
      "Model deployment",
      "MLOps",
      "Feature engineering",
      "Model monitoring",
      "Drift detection",
      "Kubernetes",
      "Docker",
      "MLflow",
      "Airflow",
      "Batch inference",
      "Real-time inference",
      "A/B testing",
      "GPU training",
      "Model versioning",
      "Data pipelines",
    ],
    exampleBullets: [
      "Deployed real-time inference APIs on Kubernetes with autoscaling, sustaining p99 latency under 120ms at 2k RPS.",
      "Built feature pipelines in Python and Airflow, cutting training-serving skew incidents by 45% quarter-over-quarter.",
      "Implemented drift and performance monitoring with automated retrain triggers, reducing silent model degradation events.",
      "Optimized PyTorch training jobs on GPU clusters, lowering epoch wall-clock time by 32% without accuracy loss.",
      "Partnered with platform teams on MLflow model registry and release gates, improving rollback time from hours to minutes.",
      "Designed batch scoring jobs processing 8M+ rows nightly with SLA alerts tied to business KPI dashboards.",
    ],
    keywordMistakes: [
      "Notebook-only keywords with no production or serving proof.",
      "Listing every framework without deployment or monitoring context.",
      "Using ‘machine learning’ without model type, metric, or business outcome.",
      "Omitting MLOps terms when the JD owns platform reliability.",
    ],
    keywordClusters: {
      data: ["Feature engineering", "Model evaluation", "Experiment tracking", "Data quality", "SQL"],
      tools: ["Python", "PyTorch", "TensorFlow", "MLflow", "Kubernetes", "Docker"],
      concepts: ["Model deployment", "MLOps", "Drift monitoring", "Batch inference", "Real-time serving"],
    },
  },
  "devops-engineer": {
    tools: ["Terraform", "Kubernetes", "AWS", "Prometheus", "GitHub Actions"],
    domainVerbs: ["automated", "provisioned", "hardened", "observed", "recovered"],
    examplePhrases: [
      "Automated infra provisioning with reusable IaC modules.",
      "Reduced MTTR via observability and incident runbook improvements.",
      "Improved deployment cadence with safer CI/CD release controls.",
    ],
    topKeywords: [
      "Docker",
      "Kubernetes",
      "Terraform",
      "AWS",
      "CI/CD",
      "Infrastructure as Code",
      "GitHub Actions",
      "Jenkins",
      "Prometheus",
      "Grafana",
      "Helm",
      "Linux",
      "Bash",
      "Observability",
      "Incident response",
      "SRE",
      "Auto-scaling",
      "Secrets management",
      "Blue-green deployments",
      "Disaster recovery",
    ],
    exampleBullets: [
      "Implemented CI/CD pipelines using GitHub Actions and Docker, reducing average deployment time by 42% while improving rollback safety.",
      "Provisioned reusable Terraform modules for AWS environments, lowering infrastructure setup errors by 60% across teams.",
      "Led Kubernetes auto-scaling and capacity tuning, cutting monthly cloud spend by 18% without SLO regressions.",
      "Built Prometheus and Grafana alerting with runbooks, improving mean time to recovery (MTTR) from 58 to 31 minutes.",
      "Hardened secrets management and release guardrails, eliminating plaintext credential exposure in deployment workflows.",
    ],
    keywordClusters: {
      tools: ["Docker", "Kubernetes", "Terraform", "AWS", "GitHub Actions", "Prometheus", "Grafana"],
      concepts: [
        "CI/CD",
        "Infrastructure as Code",
        "Observability",
        "Incident response",
        "SRE reliability",
        "Release rollback strategy",
      ],
    },
    keywordMistakes: [
      "Keyword stuffing tools without showing reliability or delivery outcomes.",
      "Listing platforms that never appear in experience bullets.",
      "Using vague verbs instead of impact language tied to MTTR, deploy speed, or cost.",
      "Skipping core concepts like IaC, observability, and incident response from the JD.",
    ],
  },
  "full-stack-developer": {
    tools: ["React", "Node.js", "TypeScript", "PostgreSQL", "REST APIs"],
    domainVerbs: ["delivered", "integrated", "refined", "measured", "iterated"],
    examplePhrases: [
      "Delivered end-to-end features across UI, API, and data layers.",
      "Integrated analytics to measure adoption and iterate faster.",
      "Improved reliability and UX through full-stack performance work.",
    ],
    topKeywords: [
      "React",
      "Node.js",
      "TypeScript",
      "JavaScript",
      "REST APIs",
      "GraphQL",
      "PostgreSQL",
      "SQL",
      "Authentication",
      "Authorization",
      "Docker",
      "CI/CD",
      "AWS",
      "Next.js",
      "HTML",
      "CSS",
      "Unit testing",
      "Integration testing",
      "System design",
      "End-to-end delivery",
    ],
    exampleBullets: [
      "Delivered a self-serve onboarding flow across React UI and Node APIs, increasing activation by 13% in six weeks.",
      "Designed PostgreSQL schemas and REST contracts consumed by web and mobile clients, reducing integration defects by 30%.",
      "Implemented auth (OAuth2 + RBAC) and audit logging for admin tools, passing security review on first submission.",
      "Added CI/CD pipelines with automated tests (Jest, Playwright), cutting release cycle time from weekly to daily.",
      "Optimized API and query paths for dashboard pages, improving p95 load time by 40% under peak traffic.",
      "Instrumented product analytics end-to-end, enabling experiment analysis without engineering ad-hoc SQL each week.",
    ],
    keywordMistakes: [
      "Claiming full-stack without both UI and API evidence in bullets.",
      "Listing databases and frameworks never used in described projects.",
      "Ignoring auth, testing, or deployment terms common in full-stack JDs.",
      "Duplicating frontend-only keywords with no backend ownership story.",
    ],
    keywordClusters: {
      frontend: ["React", "Next.js", "TypeScript", "CSS", "Accessibility"],
      backend: ["Node.js", "REST APIs", "GraphQL", "PostgreSQL", "Caching"],
      devops: ["Docker", "CI/CD", "AWS", "Monitoring", "Infrastructure as Code"],
    },
  },
};
